<a href="https://colab.research.google.com/github/surenkutty/Pytorch-learning/blob/main/pytorch_01_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(np.__version__)
print(pd.__version__)

2.5.1+cu124
1.26.4
2.2.2


#PyTorch contain
1.Scalar  ->0   2.vector  ->[2,2]  3.Matrix  ->[[2,2],[3,3]]  4.Tensor-[[[1,2,3],[2,3,4],[4,5,6]]]

In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

##Vector is dimension


In [10]:
vector=torch.tensor([2,2])
vector
vector.shape


torch.Size([2])

In [12]:
vector.item

<function Tensor.item>

In [11]:

vector.ndim

1

##Matrix

In [13]:
matrix=torch.tensor([[1,2],
                     [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

##Tensor

In [14]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensor

In [3]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6577, 0.4250, 0.9397, 0.3001],
        [0.1386, 0.3685, 0.8231, 0.0502],
        [0.0786, 0.0874, 0.7468, 0.3273]])

In [4]:
random_tensor.ndim

2

In [5]:
random_image=torch.rand(size=(3,224,224))
random_image.shape,random_image.ndim

(torch.Size([3, 224, 224]), 3)

In [6]:
torch.rand(3,4)

tensor([[0.6237, 0.9760, 0.3565, 0.6637],
        [0.3086, 0.2637, 0.9102, 0.3041],
        [0.9035, 0.4341, 0.0186, 0.1793]])

#Zeros and Ones


In [11]:
#creat a tensor are all zeros
zeross=torch.zeros(size=(3,4))
zeross

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeross*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#create a tensor all ones

oness=torch.ones(size=(3,4))
oness

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
oness.dtype

torch.float32

##Creating a Range of tensors and Tensors_like

In [21]:
#use torch.arange(start,end,step)

one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#create a Tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor DataTypes
**Note** Tensors datatypes is one of the 3 big errors you'll run into with pytorch*deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [24]:
#float 32 Tensor    its is default dynamicaly align float32 but you can change
float_32_tensor=torch.tensor([3.0,4.0,5.0],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [29]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)  #if you can change dtype for any like dtype=torch.float32 or dtype=torch.int64
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
int_32_tensor.dtype

torch.int32

##Tensor Attributes



In [34]:
#create a tensor

some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5516, 0.5351, 0.2714, 0.2102],
        [0.8433, 0.9443, 0.4253, 0.8856],
        [0.7287, 0.7720, 0.9836, 0.8175]])

In [35]:
#Find out details about Some tensors
print(some_tensor)
print(f"DataType of sensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")


tensor([[0.5516, 0.5351, 0.2714, 0.2102],
        [0.8433, 0.9443, 0.4253, 0.8856],
        [0.7287, 0.7720, 0.9836, 0.8175]])
DataType of sensor:torch.float32
Shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


#Manipulating Tensors(tensor operations)

Tensor Operations Included:
* Additon
* Substraction
* Multiplication(element_wise)
* Division
* Matrix multiplication

In [37]:
#Addition

tensors=torch.tensor([1,2,3])
tensors+10

tensor([11, 12, 13])

In [38]:
#multiply tensor by 10

tensors*10

tensor([10, 20, 30])

In [39]:
#substarct with 10
tensors-10

tensor([-9, -8, -7])

In [45]:
#Use with inbuild-functions
addt=torch.add(tensors,5)
print(addt)
torch.mul(tensors,10)

tensor([6, 7, 8])


tensor([10, 20, 30])

##Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.Element wise multiplication

2.Matrix multiplication(dot product)


In [47]:
#Element wise multiplication
print(tensors,"*",tensors)
print(tensors*tensors)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [49]:
#matrix Multiplication
torch.matmul(tensors,tensors)

tensor(14)

In [52]:
%%time
value=0
for i in range(len(tensors)):
  value +=tensors[i]*tensors[i]
print(value)

tensor(14)
CPU times: user 4.27 ms, sys: 9 µs, total: 4.28 ms
Wall time: 4.57 ms


In [53]:
%%time
torch.matmul(tensors,tensors)

CPU times: user 699 µs, sys: 0 ns, total: 699 µs
Wall time: 489 µs


tensor(14)